source 'https://supermarket.chef.io'

cookbook 'cumulocity', path: '../cumulocity-cookbooks/cumulocity'
cookbook 'cumulocity-monit', path: '../cumulocity-cookbooks/cumulocity-monit'
cookbook 'cumulocity-monitoring-agent', path: '../cumulocity-cookbooks/cumulocity-monitoring-agent'
cookbook 'cumulocity-backup-script', path: '../cumulocity-cookbooks/cumulocity-backup-script'
cookbook 'cumulocity-kubernetes', path: '../cumulocity-cookbooks/cumulocity-kubernetes'
cookbook 'cumulocity-ssagents', path: '../cumulocity-cookbooks/cumulocity-ssagents'
cookbook 'cumulocity-rsyslog', path: '../cumulocity-cookbooks/cumulocity-rsyslog'
cookbook 'cumulocity-opsmanager', path: '../cumulocity-cookbooks/cumulocity-opsmanager'
cookbook 'cumulocity-chaos-monkey', path: '../cumulocity-cookbooks/cumulocity-chaos-monkey'
cookbook 'cumulocity-filebeat', path: '../cumulocity-cookbooks/cumulocity-filebeat'

cookbook 'graylog2', '~> 2.4.5'
cookbook 'sc-mongodb', '~> 1.2.0'
cookbook 'elasticsearch-cluster', '~> 0.5.6'
cookbook 'build-essential', '~> 8.2.1'
cookbook 'seven_zip', '~> 3.0.0'
cookbook 'mingw', '~> 2.1.0'
cookbook 'chef-sugar', '~> 4.1.0'
cookbook 'ark', '~> 4.0.0'
cookbook 'authbind', '~> 0.1.10'
cookbook 'cron', '~> 4.1.3'
cookbook 'yum-epel', '~> 2.1.2'
